# Generated by Django 4.0.4 on 2022-09-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=50)),
                ('s_gender', models.CharField(max_length=10)),
                ('s_phone', models.CharField(max_length=20)),
                ('s_address', models.CharField(max_length=200)),
                ('s_username', models.CharField(max_length=20)),
                ('s_passwd', models.CharField(max_length=20)),
            ],
        ),
    ]
